const chinese = {
    signUpLanguageConfig:{
        signUp:"報名",
        userNamePlaceholder:"輸入您的姓名",
        emailAddressPlaceholder:"輸入您的電子郵件地址",
        passwordPlaceholder:"輸入您能記住的密碼",
        phoneNumber:"輸入您的電話號碼",
        buttonInnerText:"加工...",
        inputUsernameLabel:"使用者名稱:",
        inputEmailLabel:"電子郵件地址：",
        inputPasswordLabel:"密碼:",
        inputPhoneLabel:"電話號碼：",
    },
    loginLanguageConfig:{
        login:"登入",
        emailAddressPlaceholder:"輸入您的電子郵件",
        passwordPlaceholder:"輸入您的密碼",
        checkBoxInnerText:"顯示密碼",
        title:"點我看輸入的密碼",
        paragraphText:"點擊下面的開關/按鈕即可查看您輸入的密碼👎。",
        buttonInnerText:"正在驗證...",
        loginEmailInputLabel:"電子郵件地址：",
        loginPasswordInputLabel:"密碼:",
    },
    authLanguageConfig:{
        isSignup:"報名",
        isLogin:"登入",
        buttonInnerTextLogin:"登入",
        buttonInnerTextSignup:"報名",
        paragraphTextAlready:"已有帳戶？",
        paragraphTextDonT:"沒有帳戶？"
    },
    getAUserLanguageConfig:{
        paragraphText:"點擊下面的按鈕以獲取您的詳細資訊。",
        buttonTitleDisabled:"🚫 正在處理，請稍候！ ........",
        buttonTitle:"點擊此處獲取👆",
        buttonInnerText:"正在處理，請稍候！ ........",
        userNameResponseLi:"使用者名稱:",
        emailResponseLi:"電子郵件:",
        phoneResponseLi:"電話:",
        adminResponseLi:"行政:",
        adminRespYes:"是的",
        adminRespNo:"不",
        hasFetch:"重新獲取",
        hasNotFetch:"拿來"
    },
    getAllUsersLanguageConfig:{
        searchPlaceholder:"搜尋用戶",
        buttonInnerTextSearching:"正在搜尋...",
        buttonInnerTextSearch:"搜尋"
    },
    usersCardsLanguageConfig:{
        username:"使用者名稱:",
        email:"電子郵件:",
        phone:"電話:",
        admin:"行政:",
        adminYes:"是的",
        adminNo:"不",
        createdAt:"創建於:"  
    },
    descriptionOfProject:"預約系統是一款功能強大的網頁應用，旨在簡化跨行業的預約流程。無論是預約醫療諮詢、教育諮詢、商業策略會議，或是申請電子產品維修等到府服務，使用者都可以無縫瀏覽可用服務、查看重要資訊並確認預約。該系統在設計時充分考慮了響應速度、便利性和用戶體驗，旨在為服務提供者提供有序的預約安排，並為客戶提供直覺、輕鬆的預約體驗。",
    homePageDescription:"歡迎使用預約系統。這是一個一體化平台，可快速預約醫療保健、教育、商務諮詢和房屋維修等服務。只需輕按幾下，即可節省時間、保持井然有序並獲得所需的幫助。",
    educationAppointment:{
        careerTitle:"職業諮詢",
        careerDescription:"獲得個人化的職涯發展建議！無論您是在探索新機會、打造履歷，還是準備面試，我們的職業諮詢服務都能助您邁出職涯的下一步。",
        careerBooking:"立即按此預約！",
        academicTitle:"學術指導",
        academicDescription:"助力您實現學業目標！我們的學業諮詢課程將指導您選擇課程、了解學位要求，並規劃您的畢業之路。獲得學業成功所需的支持。",
        academicBooking:"立即按此預約！",
        oneOnOneTitle:"一對一輔導",
        oneOnOneDescription:"學習困難？我們的一對一輔導課程提供客製化支持，幫助您理解難題，提高成績，增強自信。立即預約導師！",
        oneOnOneBooking:"立即按此預約！",
    },
    healthcareAppointment:{
        vaccinationTitle:"疫苗接種",
        vaccinationDescription:"及時接種疫苗，保護您和家人的安全。預約由合格的醫療保健專業人員進行常規或旅行相關的免疫接種。",
        vaccinationBooking:"立即按此預約！",
        consultationTitle:"諮詢",
        consultationDescription:"需要醫療建議？預約一位持牌醫療保健提供者的諮詢，討論症狀、獲取診斷或獲得有關您的健康問題的專業指導。",
        consultationBooking:"立即按此預約！",
        counselingTitle:"諮詢會議",
        counselingDescription:"呵護您的心理健康。我們的諮商服務為您提供安全且私密的空間，讓您與訓練有素的諮商師暢談壓力、焦慮、人際關係或其他個人挑戰。",
        counselingBooking:"立即按此預約！",
        dentalTitle:"牙科保健",
        dentalDescription:"保持健康笑容！預約牙科服務，包括潔牙、牙齒檢查、補牙或其他口腔護理。我們的牙科專家將竭誠為您服務，確保您的牙齒和牙齦保持健康。",
        dentalBooking:"立即按此預約！",
        physiotherapyTitle:"物理治療",
        physiotherapyDescription:"透過專業的物理治療，恢復並重拾力量。無論是傷後復健、慢性疼痛或行動不便，我們的物理治療師都能幫助您更好地活動，感覺更舒適。",
        physiotherapyBooking:"立即按此預約！"
    },
    professionalServiceAppointment:{
        businessConsultTitle:"商業諮詢",
        businessConsultDescription:"取得專家洞見，幫助您發展業務。無論您是新創公司或成熟企業，我們的業務顧問都能提供策略指導、問題解決和規劃支持，助您有效擴展業務，實現目標。",
        businessConsultBooking:"立即按此預約！",
        financialAdvisingTitle:"財務諮詢",
        financialAdvisingDescription:"透過專業建議掌控您的財務狀況。我們認證的財務顧問將協助您規劃未來、管理投資、減少債務，並做出明智的決策，確保您的財務狀況良好。",
        financialAdvisingBooking:"立即按此預約！",
        realEstateAgentTitle:"房地產經紀人",
        realEstateAgentDescription:"安心找到您的理想物件。我們經驗豐富的房仲提供個人化服務，助您買賣或租賃住宅及商業空間，並運用當地專業知識，全程引導您完成每一步。",
        realEstateAgentBooking:"立即按此預約！",
    },
    technicalAppointment:{
        electricalElectronicsTitle:"電氣/電子產品維修",
        electricalElectronicsDescription:"電器或設備故障了嗎？我們的電氣和電子產品維修服務提供快速可靠的維修服務，涵蓋從線路問題到設備損壞的各種問題。預約經驗豐富的技術人員，讓一切恢復正常。",
        electricalElectronicsBooking:"立即按此預約！",
        homeServiceTitle:"上門服務",
        homeServiceDescription:"在家即可享受便捷！無論是清潔、管道、維修或雜工，我們的專業上門服務人員都會上門為您服務，省時省力，同時確保您的家居品質和舒適度。",
        homeServiceBooking:"立即按此預約！",
    },
    appointmentHeadings:{
        educationAppointmentHeading  : "教育任命",
        healthcareAppointmentHeading : "醫療保健預約",
        professionalServiceHeading   : "專業服務預約",
        technicalAppointmentHeading  : "技術維修預約"
    },
    userNetworkStatus:{
        status  : "地位",
        online  : "在線的",
        offline : "離線"
    },
    userProfileInfo:{
        userProfileHeading : "用戶資料：",
        userProfileParagraph : "為了在這裡查看您的詳細信息, 您必須通過單擊主頁右上角側邊欄 (3 個垂直點）中的“用戶資料”來獲取您的詳細信息。",
        userProfileName     : "姓名：",
        userProfileEmail    : "電子郵件：",
        userProfileTel      : "電話：",
        userProfileAdmin    : "行政",
        userProfileNonAdmin : "非管理員",
        userProfilePassword : "密碼："
    },
    appointmentsInputFields:{
        appointmentsGenderLabel                     : "性別：",
        appointmentsGenderPlaceHolder               : "請輸入您的性別",
        appointmentsAddressLabel                    : "地址：",
        appointmentsAddressPlaceHolder              : "請輸入您的地址",
        appointmentsNextOfKinLabel                  : "近親：",
        appointmentsNextOfKinPlaceHolder            : "請輸入您的近親的姓名",
        appointmentsNextOfKinAddressLabel           : "近親地址：",
        appointmentsNextOfKinAddressPlaceHolder     : "請輸入您的近親地址",
        appointmentsNextOfKinPhoneNumberLabel       : "近親電話號碼：",
        appointmentsNextOfKinPhoneNumberPlaceHolder : "請輸入您的近親電話號碼",
        appointmentsTimeLabel                       : "預約時間：",
        appointmentsTimePlaceHolder                 : "請選擇您方便的時間",
        appointmentsDateLabel                       : "預約日期：",
        appointmentsDatePlaceHolder                 : "請選擇您方便的日期",
        appointmentsDescriptionLabel                : "預約描述：",
        appointmentsDescriptionPlaceHolder          : "請寫下預約描述",
        appointmentButtonParagraph                  : "加工....",
        appointmentButtonInnerText                  : "提交",
        academicAdvisingHeading                     : "學術指導任命",
        businessConsultationHeading                 : "業務諮詢預約",
        careerCounselingHeading                     : "職業諮詢預約",
        electricalElectronicsRepairHeading          : "電器/電子產品維修預約",
        financialAdvisoryHeading                    : "財務顧問任命",
        HealthcareConsultationHeading               : "醫療保健諮詢預約",
        healthcareCounselingSessionHeading          : "醫療保健諮詢會談預約",
        healthcareDentalHeading                     : "牙科保健預約",
        healthcarePhysiotherapySessionHeading       : "醫療保健物理治療療程預約",
        healthcareVaccinationHeading                : "醫療保健疫苗接種預約",
        homeServiceHeading                          : "到府服務預約",
        oneOnOneTutoringSessionHeading              : "一對一輔導課程預約",
        realEstateAgentHeading                      : "房地產經紀人預約"
    },
}
export default chinese;