const eng = {
    signUpLanguageConfig:{
        signUp:"SignUp",
        userNamePlaceholder:"Enter your name",
        emailAddressPlaceholder:"Enter your email address",
        passwordPlaceholder:"Enter a password that you can remember",
        phoneNumber:"Enter your phone number",
        buttonInnerText:"Processing...",
        inputUsernameLabel:"Username:",
        inputEmailLabel:"Email-address:",
        inputPasswordLabel:"Password:",
        inputPhoneLabel:"Phone-number:",
    },
    loginLanguageConfig:{
        login:"Login",
        emailAddressPlaceholder:"Enter your email",
        passwordPlaceholder:"Enter your password",
        checkBoxInnerText:"Show Password",
        title:"Click me to see the password entered",
        paragraphText:"click the below switch/button to see the password 👎you entered.",
        buttonInnerText:"Authenticating...",
        loginEmailInputLabel:"Email-address:",
        loginPasswordInputLabel:"Password:",
    },
    authLanguageConfig:{
        isSignup:"Sign up",
        isLogin:"Login",
        buttonInnerTextLogin:"Login",
        buttonInnerTextSignup:"Sign Up",
        paragraphTextAlready:"Already have an account?",
        paragraphTextDonT:"Don't have an account?"
    },
    getAUserLanguageConfig:{
        paragraphText:"click the button below to fetch your details.",
        buttonTitleDisabled:"🚫 Processing, please wait...",
        buttonTitle:"Click here to fetch👆",
        buttonInnerText:"Processing, please wait!....",
        userNameResponseLi:"Username:",
        emailResponseLi:"Email:",
        phoneResponseLi:"Phone:",
        adminResponseLi:"Admin:",
        adminRespYes:"Yes",
        adminRespNo:"No",
        hasFetch:"Refetch",
        hasNotFetch:"Fetch"
    },
    getAllUsersLanguageConfig:{
        searchPlaceholder:"Search users",
        buttonInnerTextSearching:"Searching...",
        buttonInnerTextSearch:"Search"
    },
    usersCardsLanguageConfig:{
        username:"Username:",
        email:"Email-address:",
        phone:"Phone-number:",
        admin:"Admin",
        adminYes:"Yes",
        adminNo:"No",
        createdAt:"Created-at:" 
    },
    descriptionOfProject:"Appointment Booking System is a versatile web-based application built to streamline the process of scheduling appointments across multiple sectors. Whether it's booking a medical consultation, educational advising, business strategy session, or requesting a home service like electronics repair, users can explore available services, view essential details, and confirm appointments seamlessly. Designed with responsiveness, accessibility, and user experience in mind, the system benefits both service providers through organized scheduling and clients through an intuitive, stress-free booking experience.",
    homePageDescription:"Welcome to Appointment Booking System. Your all-in-one platform to quickly book services like healthcare, education, business consultations, and home repairs. Save time, stay organized, and get the help you need with just a few taps.",
    educationAppointment:{
        careerTitle:"Career Counseling",
        careerDescription:"Get personalized advice on your career journey! Whether you're exploring new opportunities, building your resume, or preparing for interviews, our Career Counseling sessions are here to help you take the next step in your professional life.",
        careerBooking:"Click here to book appointment now!.",
        academicTitle:"Academic Advising",
        academicDescription:"Stay on track with your academic goals! Our Academic Advising sessions guide you through course selection, degree requirements, and planning your path to graduation. Get the support you need to succeed in your studies.",
        academicBooking:"Click here to book appointment now!.",
        oneOnOneTitle:"One-On-One-Tutoring",
        oneOnOneDescription:"Struggling with a subject? Our One-on-One Tutoring sessions provide tailored support to help you understand difficult topics, improve your grades, and boost your confidence. Book a session with a tutor today!.",
        oneOnOneBooking:"Click here to book appointment now!.",
    },
    healthcareAppointment:{
        vaccinationTitle:"Vaccination",
        vaccinationDescription:"Protect yourself and your loved ones with timely vaccinations. Book an appointment to receive routine or travel-related immunizations administered by qualified healthcare professionals.",
        vaccinationBooking:"Click here to book appointment now!.",
        consultationTitle:"Consultation",
        consultationDescription:"Need medical advice? Schedule a consultation with a licensed healthcare provider to discuss symptoms, get diagnoses, or receive professional guidance on your health concerns.",
        consultationBooking:"Click here to book appointment now!.",
        counselingTitle:"Counseling Session",
        counselingDescription:"Take care of your mental well-being. Our Counseling Sessions offer a safe, confidential space to talk to trained counselors about stress, anxiety, relationships, or other personal challenges.",
        counselingBooking:"Click here to book appointment now!.",
        dentalTitle:"Dental Healthcare",
        dentalDescription:"Keep your smile healthy! Book a dental appointment for cleanings, check-ups, fillings, or other oral care needs. Our dental professionals are here to ensure your teeth and gums stay in great shape.",
        dentalBooking:"Click here to book appointment now!.",
        physiotherapyTitle:"Physiotherapy",
        physiotherapyDescription:"Recover and regain strength with expert physiotherapy. Whether it's post-injury rehab, chronic pain, or mobility issues, our therapists will help you move better and feel better.",
        physiotherapyBooking:"Click here to book appointment now!.",
    },
    professionalServiceAppointment:{
        businessConsultTitle:"Business Consultation",
        businessConsultDescription:"Get expert insights to grow your business. Whether you're a startup or an established company, our business consultants offer strategic guidance, problem-solving, and planning support to help you scale effectively and achieve your goals.",
        businessConsultBooking:"Click here to book appointment now!.",
        financialAdvisingTitle:"Financial Advising",
        financialAdvisingDescription:"Take control of your finances with professional advice. Our certified financial advisors help you plan for the future, manage investments, reduce debt, and make informed decisions to secure your financial well-being.",
        financialAdvisingBooking:"Click here to book appointment now!.",
        realEstateAgentTitle:"Real Estate Agent",
        realEstateAgentDescription:"Find your perfect property with confidence. Our experienced real estate agents provide personalized service to help you buy, sell, or rent homes and commercial spaces — guiding you every step of the way with local expertise.",
        realEstateAgentBooking:"Click here to book appointment now!.",
    },
    technicalAppointment:{
        electricalElectronicsTitle:"Electrical/Electronics Repair",
        electricalElectronicsDescription:"Got a faulty appliance or device? Our Electrical and Electronics Repair service offers fast, reliable fixes for everything from wiring issues to broken gadgets. Book a session with a skilled technician and get things working again",
        electricalElectronicsBooking:"Click here to book appointment now!.",
        homeServiceTitle:"Home service",
        homeServiceDescription:"Enjoy convenience at your doorstep! Whether it's cleaning, plumbing, maintenance, or handyman tasks, our Home Service professionals come to you—saving time and effort while ensuring quality and comfort in your home.",
        homeServiceBooking:"Click here to book appointment now!.",
    },
    appointmentHeadings:{
        educationAppointmentHeading  : "Educational appointment",
        healthcareAppointmentHeading : "Healthcare appointment",
        professionalServiceHeading   : "Professional service appointment",
        technicalAppointmentHeading  : "Technical repair appointment"
    },
    userNetworkStatus:{
        status  : "Status",
        online  : "Online",
        offline : "Offline"
    },
    userProfileInfo:{
        userProfileHeading : "User Profile:",
        userProfileName     : "NAME:",
        userProfileEmail    : "EMAIL:",
        userProfileTel      : "TELEPHONE:",
        userProfileAdmin    : "Admin",
        userProfileNonAdmin : "Non-Admin",
        userProfilePassword : "PASSWORD:"
    },
    appointmentsInputFields:{
        appointmentsGenderLabel                     : "Gender:",
        appointmentsGenderPlaceHolder               : "Please enter your gender",
        appointmentsAddressLabel                    : "Address:",
        appointmentsAddressPlaceHolder              : "Please enter Your address",
        appointmentsNextOfKinLabel                  : "Next Of Kin:",
        appointmentsNextOfKinPlaceHolder            : "Please enter the name of your next of kin",
        appointmentsNextOfKinAddressLabel           : "Next Of Kin Address:",
        appointmentsNextOfKinAddressPlaceHolder     : "Please enter your next of kin address",
        appointmentsNextOfKinPhoneNumberLabel       : "Next Of Kin Phone Number:",
        appointmentsNextOfKinPhoneNumberPlaceHolder : "Please enter your next of kin phone number",
        appointmentsTimeLabel                       : "Appointment Time:",
        appointmentsTimePlaceHolder                 : "Please choose your convenient time",
        appointmentsDateLabel                       : "Appointment Date:",
        appointmentsDatePlaceHolder                 : "Please choose your convenient date",
        appointmentsDescriptionLabel                : "Appointment Description:",
        appointmentsDescriptionPlaceHolder          : "Please write the appointment description",
        appointmentButtonParagraph                  : "Processing....",
        appointmentButtonInnerText                  : "Submit",
        academicAdvisingHeading                     : "Academic-Advising Appointment",
        businessConsultationHeading                 : "Business Consultation  Appointment",
        careerCounselingHeading                     : "Career-Counseling Appointment",
        electricalElectronicsRepairHeading          : "Electrical/Electronics Repair Appointment",
        financialAdvisoryHeading                    : "Financial Advisory Appointment",
        HealthcareConsultationHeading               : "Healthcare Consultation Appointment",
        healthcareCounselingSessionHeading          : "Healthcare Counseling Session Appointment",
        healthcareDentalHeading                     : "Dental Healthcare Appointment",
        healthcarePhysiotherapySessionHeading       : "Healthcare Physiotherapy Session Appointment",
        healthcareVaccinationHeading                : "Healthcare Vaccination Appointment",
        homeServiceHeading                          : "Home Service Appointment",
        oneOnOneTutoringSessionHeading              : "One-On-One Tutoring Session Appointment",
        realEstateAgentHeading                      : "Real Estate Agent Appointment"
    },
}
export default eng;