const french = {
    signUpLanguageConfig:{
        signUp:"S'inscrire",
        userNamePlaceholder:"Entrez votre nom",
        emailAddressPlaceholder:"Entrez votre adresse e-mail",
        passwordPlaceholder:"Entrez un mot de passe dont vous vous souviendrez",
        phoneNumber:"Entrez votre numéro de téléphone",
        buttonInnerText:"Traitement...",
        inputUsernameLabel:"Nom d'utilisateur:",
        inputEmailLabel:"Adresse e-mail:",
        inputPasswordLabel:"Mot de passe:",
        inputPhoneLabel:"Numéro de téléphone :",
    },
    loginLanguageConfig:{
        login:"Se connecter",
        emailAddressPlaceholder:"Entrez votre email",
        passwordPlaceholder:"Entrez votre mot de passe",
        checkBoxInnerText:"Afficher le mot de passe",
        title:"Cliquez ici pour voir le mot de passe saisi",
        paragraphText:"Cliquez sur le commutateur/bouton ci-dessous pour voir le mot de passe 👎 que vous avez saisi.",
        buttonInnerText:"Authentification...",
        loginEmailInputLabel:"Adresse e-mail:",
        loginPasswordInputLabel:"Mot de passe:",
    },
    authLanguageConfig:{
        isSignup:"S'inscrire",
        isLogin:"Se connecter",
        buttonInnerTextLogin:"Se connecter",
        buttonInnerTextSignup:"S'inscrire",
        paragraphTextAlready:"Vous avez déjà un compte ?",
        paragraphTextDonT:"Vous n'avez pas de compte ?"
    },
    getAUserLanguageConfig:{
        paragraphText:"Cliquez sur le bouton ci-dessous pour récupérer vos coordonnées.",
        buttonTitleDisabled:"🚫 Traitement en cours, veuillez patienter !........",
        buttonTitle:"Cliquez ici pour récupérer👆",
        buttonInnerText:"Traitement en cours, veuillez patienter !........",
        userNameResponseLi:"Nom d'utilisateur:",
        emailResponseLi:"E-mail:",
        phoneResponseLi:"Téléphone:",
        adminResponseLi:"Administrateur:",
        adminRespYes:"Oui",
        adminRespNo:"Non",
        hasFetch:"Récupérer",
        hasNotFetch:"Aller chercher"
    },
    getAllUsersLanguageConfig:{
        searchPlaceholder:"Rechercher des utilisateurs",
        buttonInnerTextSearching:"Recherche...",
        buttonInnerTextSearch:"Recherche"
    },
    usersCardsLanguageConfig:{
        username:"Nom d'utilisateur:",
        email:"E-mail:",
        phone:"Téléphone:",
        admin:"Administrateur:",
        adminYes:"Oui",
        adminNo:"Non",
        createdAt:"Créé à :"  
    },
    descriptionOfProject:"Appointment Booking System est une application web polyvalente conçue pour simplifier la prise de rendez-vous dans de nombreux secteurs. Qu'il s'agisse de réserver une consultation médicale, des conseils pédagogiques, une séance de stratégie commerciale ou une demande de service à domicile comme la réparation d'appareils électroniques, les utilisateurs peuvent explorer les services disponibles, consulter les informations essentielles et confirmer leurs rendez-vous en toute simplicité. Conçu pour être réactif, accessible et optimiser l'expérience utilisateur, ce système offre aux prestataires de services une planification organisée et aux clients une expérience de réservation intuitive et sans stress.",
    homePageDescription:"Bienvenue sur Appointment Booking System. Votre plateforme tout-en-un pour réserver rapidement des services comme les soins de santé, l'éducation, les consultations professionnelles et les réparations à domicile. Gagnez du temps, restez organisé et obtenez l'aide dont vous avez besoin en quelques clics.",
    educationAppointment:{
        careerTitle:"Orientation professionnelle",
        careerDescription:"Bénéficiez de conseils personnalisés pour votre parcours professionnel! Que vous exploriez de nouvelles opportunités, que vous prépariez votre CV ou vos entretiens d'embauche, nos séances d'orientation professionnelle sont là pour vous aider à franchir une nouvelle étape dans votre vie professionnelle.",
        careerBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
        academicTitle:"Conseils pédagogiques",
        academicDescription:"Gardez le cap sur vos objectifs académiques! Nos séances de conseil pédagogique vous guident dans le choix de vos cours, les exigences du diplôme et la planification de votre parcours. Obtenez le soutien nécessaire pour réussir vos études.",
        academicBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
        oneOnOneTitle:"Tutorat individuel",
        oneOnOneDescription:"Vous avez des difficultés avec une matière ? Nos séances de tutorat individuel vous offrent un soutien personnalisé pour vous aider à comprendre les sujets difficiles, améliorer vos notes et renforcer votre confiance en vous. Réservez une séance avec un tuteur dès aujourd'hui !",
        oneOnOneBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
    },
    healthcareAppointment:{
        vaccinationTitle:"Vaccination",
        vaccinationDescription:"Protégez-vous et vos proches grâce à la vaccination à temps. Prenez rendez-vous pour recevoir vos vaccins de routine ou de voyage, administrés par des professionnels de santé qualifiés.",
        vaccinationBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
        consultationTitle:"Consultation",
        consultationDescription:"Besoin d'un avis médical? Prenez rendez-vous avec un professionnel de santé agréé pour discuter de vos symptômes, obtenir un diagnostic ou bénéficier de conseils professionnels sur vos problèmes de santé.",
        consultationBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
        counselingTitle:"Séance de conseil",
        counselingDescription:"Prenez soin de votre bien-être mental. Nos séances de conseil offrent un espace sûr et confidentiel pour discuter avec des thérapeutes qualifiés de votre stress, de votre anxiété, de vos relations ou d'autres difficultés personnelles.",
        counselingBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
        dentalTitle:"soins dentaires",
        dentalDescription:"Gardez un sourire éclatant! Prenez rendez-vous chez le dentiste pour un nettoyage, un contrôle, des obturations ou tout autre soin bucco-dentaire. Nos dentistes sont là pour veiller à ce que vos dents et vos gencives restent en pleine forme.",
        dentalBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
        physiotherapyTitle:"Physiothérapie",
        physiotherapyDescription:"Récupérez et retrouvez votre force grâce à une physiothérapie experte. Qu'il s'agisse de rééducation post-blessure, de douleurs chroniques ou de problèmes de mobilité, nos thérapeutes vous aideront à mieux bouger et à vous sentir mieux.",
        physiotherapyBooking:"Cliquez ici pour prendre rendez-vous maintenant!"
    },
    professionalServiceAppointment:{
        businessConsultTitle:"Consultation d'affaires",
        businessConsultDescription:"Bénéficiez de l'expertise d'experts pour développer votre activité. Que vous soyez une start-up ou une entreprise établie, nos consultants vous proposent des conseils stratégiques, une aide à la résolution de problèmes et un soutien à la planification pour vous aider à évoluer efficacement et à atteindre vos objectifs.",
        businessConsultBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
        financialAdvisingTitle:"Conseil financier",
        financialAdvisingDescription:"Prenez le contrôle de vos finances grâce à des conseils professionnels. Nos conseillers financiers certifiés vous aident à planifier votre avenir, à gérer vos investissements, à réduire vos dettes et à prendre des décisions éclairées pour assurer votre bien-être financier.",
        financialAdvisingBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
        realEstateAgentTitle:"Agent immobilier",
        realEstateAgentDescription:"Trouvez le bien idéal en toute confiance. Nos agents immobiliers expérimentés vous offrent un service personnalisé pour vous aider à acheter, vendre ou louer des maisons et des locaux commerciaux, en vous guidant à chaque étape grâce à leur expertise locale.",
        realEstateAgentBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
    },
    technicalAppointment:{
        electricalElectronicsTitle:"Réparation électrique/électronique",
        electricalElectronicsDescription:"Vous avez un appareil défectueux ? Notre service de réparation électrique et électronique propose des solutions rapides et fiables pour tous vos problèmes, des problèmes de câblage aux appareils cassés. Prenez rendez-vous avec un technicien qualifié et remettez tout en état de marche.",
        electricalElectronicsBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
        homeServiceTitle:"Service à domicile",
        homeServiceDescription:"Profitez du confort à votre porte ! Nettoyage, plomberie, entretien ou bricolage : nos professionnels du service à domicile se déplacent chez vous pour vous faire gagner du temps et vous assurer confort et qualité.",
        homeServiceBooking:"Cliquez ici pour prendre rendez-vous maintenant!",
    },
    appointmentHeadings:{
        educationAppointmentHeading  : "Nomination pédagogique",
        healthcareAppointmentHeading : "Rendez-vous médical",
        professionalServiceHeading   : "Rendez-vous de service professionnel",
        technicalAppointmentHeading  : "Rendez-vous de réparation technique"
    },
    userNetworkStatus:{
        status  : "Statut",
        online  : "En ligne",
        offline : "Hors ligne"
    },
    userProfileInfo:{
        userProfileHeading : "Profil utilisateur :",
        userProfileName     : "NOM:",
        userProfileEmail    : "E-MAIL:",
        userProfileTel      : "TÉLÉPHONE:",
        userProfileAdmin    : "Administrateur",
        userProfileNonAdmin : "Non-administrateur",
        userProfilePassword : "MOT DE PASSE:"
    },
    appointmentsInputFields:{
        appointmentsGenderLabel                     : "Genre:",
        appointmentsGenderPlaceHolder               : "Veuillez entrer votre sexe",
        appointmentsAddressLabel                    : "Adresse:",
        appointmentsAddressPlaceHolder              : "Veuillez entrer votre adresse",
        appointmentsNextOfKinLabel                  : "Plus proche parent :",
        appointmentsNextOfKinPlaceHolder            : "Veuillez entrer le nom de votre plus proche parent",
        appointmentsNextOfKinAddressLabel           : "Adresse du plus proche parent :",
        appointmentsNextOfKinAddressPlaceHolder     : "Veuillez saisir l'adresse de votre plus proche parent",
        appointmentsNextOfKinPhoneNumberLabel       : "Numéro de téléphone du plus proche parent :",
        appointmentsNextOfKinPhoneNumberPlaceHolder : "Veuillez entrer le numéro de téléphone de votre plus proche parent",
        appointmentsTimeLabel                       : "Heure du rendez-vous :",
        appointmentsTimePlaceHolder                 : "Veuillez choisir l'heure qui vous convient",
        appointmentsDateLabel                       : "Date de rendez-vous :",
        appointmentsDatePlaceHolder                 : "Veuillez choisir la date qui vous convient",
        appointmentsDescriptionLabel                : "Description du rendez-vous :",
        appointmentsDescriptionPlaceHolder          : "Veuillez écrire la description du rendez-vous",
        appointmentButtonParagraph                  : "Traitement....",
        appointmentButtonInnerText                  : "Soumettre",
        academicAdvisingHeading                     : "Nomination de conseiller pédagogique",
        businessConsultationHeading                 : "Rendez-vous de consultation d'entreprise",
        careerCounselingHeading                     : "Rendez-vous d'orientation professionnelle",
        electricalElectronicsRepairHeading          : "Rendez-vous de réparation électrique/électronique",
        financialAdvisoryHeading                    : "Nomination de conseiller financier",
        HealthcareConsultationHeading               : "Rendez-vous de consultation médicale",
        healthcareCounselingSessionHeading          : "Rendez-vous pour une séance de conseil en soins de santé",
        healthcareDentalHeading                     : "Rendez-vous pour soins dentaires",
        healthcarePhysiotherapySessionHeading       : "Rendez-vous pour une séance de physiothérapie en santé",
        healthcareVaccinationHeading                : "Rendez-vous de vaccination pour les soins de santé",
        homeServiceHeading                          : "Rendez-vous de service à domicile",
        oneOnOneTutoringSessionHeading              : "Rendez-vous pour une séance de tutorat individuel",
        realEstateAgentHeading                      : "Rendez-vous avec un agent immobilier"
    },
}
export default french;