const hausa = {
    signUpLanguageConfig:{
        signUp:"Shiga",
        userNamePlaceholder:"Shigar da sunan ku",
        emailAddressPlaceholder:"Shigar da adireshin imel ɗin ku",
        passwordPlaceholder:"Shigar da kalmar sirri da za ku iya tunawa",
        phoneNumber:"Shigar da lambar wayar ku",
        buttonInnerText:"Ana aiwatarwa...",
        inputUsernameLabel:"Sunan mai amfani:",
        inputEmailLabel:"Adireshin i-mel:",
        inputPasswordLabel:"Kalmar wucewa:",
        inputPhoneLabel:"Lambar tarho:",
    },
    loginLanguageConfig:{
        login:"Shiga",
        emailAddressPlaceholder:"Shigar da imel ɗin ku",
        passwordPlaceholder:"Shigar da kalmar wucewa",
        checkBoxInnerText:"Nuna Kalmar wucewa",
        title:"Danna ni don ganin kalmar sirrin da aka shigar",
        paragraphText:"danna maballin kunnawa na ƙasa don ganin kalmar sirri 👎 da kuka shigar.",
        buttonInnerText:"Tabbatarwa...",
        loginEmailInputLabel:"Adireshin i-mel:",
        loginPasswordInputLabel:"Kalmar wucewa:",
    },
    authLanguageConfig:{
        isSignup:"Shiga",
        isLogin:"Shiga",
        buttonInnerTextLogin:"Shiga",
        buttonInnerTextSignup:"Shiga",
        paragraphTextAlready:"Kuna da asusu?",
        paragraphTextDonT:"Ba ku da asusu?"
    },
    getAUserLanguageConfig:{
        paragraphText:"danna maɓallin da ke ƙasa don ɗauko bayananku.",
        buttonTitleDisabled:"🚫 Ana aiwatarwa, da fatan za a jira!........",
        buttonTitle:"Danna nan don debo👆",
        buttonInnerText:"Ana aiwatarwa, da fatan za a jira!........",
        userNameResponseLi:"Sunan mai amfani:",
        emailResponseLi:"Imel:",
        phoneResponseLi:"Waya:",
        adminResponseLi:"Admin:",
        adminRespYes:"Ee",
        adminRespNo:"A'a",
        hasFetch:"Refetch",
        hasNotFetch:"Dauke"
    },
    getAllUsersLanguageConfig:{
        searchPlaceholder:"Bincika masu amfani",
        buttonInnerTextSearching:"Neman...",
        buttonInnerTextSearch:"Bincika"
    },
    usersCardsLanguageConfig:{
        username:"Sunan mai amfani:",
        email:"Imel:",
        phone:"Waya:",
        admin:"Admin:",
        adminYes:"Ee",
        adminNo:"A'a",
        createdAt:"Ƙirƙiri-a:"  
    },
    descriptionOfProject:"Tsarin Buƙatar Alƙawari babban aikace-aikacen tushen gidan yanar gizo ne wanda aka gina don daidaita tsarin tsara alƙawura a sassa da yawa. Ko yana yin ajiyar shawarwarin likita, ba da shawara na ilimi, zaman dabarun kasuwanci, ko neman sabis na gida kamar gyaran kayan lantarki, masu amfani za su iya bincika ayyukan da ake da su, duba mahimman bayanai, da tabbatar da alƙawura ba tare da matsala ba. An ƙera shi tare da amsawa, samun dama, da ƙwarewar mai amfani a hankali, tsarin yana amfanar masu samar da sabis ta hanyar tsara tsarin tsarawa da abokan ciniki ta hanyar ƙwarewa, ƙwarewar ajiyar kuɗi mara damuwa.",
    homePageDescription:"Barka da zuwa Tsarin Buƙatun Alƙawari. Dandalin ku na gaba ɗaya don yin lissafin ayyuka cikin sauri kamar kiwon lafiya, ilimi, shawarwarin kasuwanci, da gyaran gida. Ajiye lokaci, kasance cikin tsari, kuma sami taimakon da kuke buƙata tare da ƴan famfo kawai.",
    educationAppointment:{
        careerTitle:"Shawarar Sana'a",
        careerDescription:"Sami nasiha na keɓaɓɓen kan tafiyar aikinku! Ko kuna binciko sabbin damammaki, gina ci gaban ku, ko kuma kuna shirin yin tambayoyi, zaman Shawarar Sana'a na nan don taimaka muku ɗaukar mataki na gaba a rayuwar ƙwararrun ku.",
        careerBooking:"Danna nan don yin alƙawari yanzu!.",
        academicTitle:"Shawarar Ilimi",
        academicDescription:"Tsaya kan hanya tare da burin ilimi! Zaman Ba ​​da Shawarwari na Ilimi ya jagorance ku ta hanyar zaɓin kwas, buƙatun digiri, da tsara hanyar ku zuwa kammala karatun. Sami tallafin da kuke buƙata don cin nasara a karatun ku.",
        academicBooking:"Danna nan don yin alƙawari yanzu!.",
        oneOnOneTitle:"Koyarwa Daya-Kan-Daya",
        oneOnOneDescription:"Famawa da wani batu? Zaman Koyarwarmu Daya-Daya-Daya tana ba da ingantaccen tallafi don taimaka muku fahimtar batutuwa masu wahala, haɓaka maki, da haɓaka kwarin gwiwa. Littafin zama tare da malami a yau!.",
        oneOnOneBooking:"Danna nan don yin alƙawari yanzu!.",
    },
    healthcareAppointment:{
        vaccinationTitle:"Alurar riga kafi",
        vaccinationDescription:"Kare kanka da masoyinka tare da allurar rigakafin kan lokaci. Yi alƙawari don karɓar rigakafi na yau da kullun ko balaguron balaguro wanda ƙwararrun ƙwararrun kiwon lafiya ke gudanarwa.",
        vaccinationBooking:"Danna nan don yin alƙawari yanzu!.",
        consultationTitle:"Shawarwari",
        consultationDescription:"Kuna buƙatar shawarar likita? Jadawalin tuntuɓar mai ba da lafiya mai lasisi don tattaunawa game da alamomi, samun alamun cutar, ko karɓar jagorar ƙwararru akan abubuwan da suka shafi lafiyar ku.",
        consultationBooking:"Danna nan don yin alƙawari yanzu!.",
        counselingTitle:"Zama Nasiha",
        counselingDescription:"Kula da lafiyar hankalin ku. Zaman Shawarwarinmu yana ba da amintaccen wuri mai sirri don magana da ƙwararrun masu ba da shawara game da damuwa, damuwa, dangantaka, ko wasu ƙalubale na sirri.",
        counselingBooking:"Danna nan don yin alƙawari yanzu!.",
        dentalTitle:"Kiwon Lafiyar hakori",
        dentalDescription:"Ka kiyaye murmushinka lafiya! Yi alƙawari na hakori don tsaftacewa, dubawa, cikawa, ko wasu buƙatun kula da baki. Kwararrun likitan mu suna nan don tabbatar da hakora da gumakan ku sun kasance cikin kyakkyawan tsari.",
        dentalBooking:"Danna nan don yin alƙawari yanzu!.",
        physiotherapyTitle:"Physiotherapy",
        physiotherapyDescription:"Farfadowa da dawo da ƙarfi tare da ƙwararrun ilimin motsa jiki. Ko gyaran gyare-gyaren bayan raunin da ya faru, ciwo mai tsanani, ko matsalolin motsi, masu kwantar da hankalinmu zasu taimake ka ka motsa da kyau kuma ka ji daɗi.",
        physiotherapyBooking:"Danna nan don yin alƙawari yanzu!."
    },
    professionalServiceAppointment:{
        businessConsultTitle:"Shawarar Kasuwanci",
        businessConsultDescription:"Samun ƙwararrun ƙwararrun don haɓaka kasuwancin ku. Ko kai mai farawa ne ko kafaffen kamfani, masu ba da shawara kan kasuwanci suna ba da jagorar dabaru, warware matsala, da tallafin tsara shirye-shirye don taimaka muku haɓaka yadda ya kamata da cimma burin ku.",
        businessConsultBooking:"Danna nan don yin alƙawari yanzu!.",
        financialAdvisingTitle:"Shawarar Kudi",
        financialAdvisingDescription:"Kula da kuɗin ku tare da shawarwarin kwararru. Ƙwararrun masu ba da shawara kan kuɗi namu suna taimaka muku yin shiri don gaba, sarrafa saka hannun jari, rage bashi, da kuma yanke shawara mai fa'ida don tabbatar da jin daɗin kuɗin ku.",
        financialAdvisingBooking:"Danna nan don yin alƙawari yanzu!.",
        realEstateAgentTitle:"Wakilin Gidaje",
        realEstateAgentDescription:"Nemo cikakkiyar kayanku tare da amincewa. Gogaggun wakilai na gidaje suna ba da sabis na keɓaɓɓen don taimaka muku siye, siyarwa, ko hayar gidaje da wuraren kasuwanci - suna jagorantar ku kowane mataki na hanya tare da ƙwarewar gida.",
        realEstateAgentBooking:"Danna nan don yin alƙawari yanzu!.",
    },
    technicalAppointment:{
        electricalElectronicsTitle:"Gyaran Wutar Lantarki/Electronics",
        electricalElectronicsDescription:"Kuna da na'ura ko na'ura mara kyau? Sabis ɗin Gyaran Wutar Lantarki da Kayan Wutar Lantarki yana ba da gyare-gyare cikin sauri, ingantaccen abin dogaro ga komai tun daga al'amuran waya zuwa na'urori masu karye. Yi wani zama tare da ƙwararren ƙwararren kuma sake samun abubuwa suyi aiki.",
        electricalElectronicsBooking:"Danna nan don yin alƙawari yanzu!.",
        homeServiceTitle:"Sabis na gida",
        homeServiceDescription:"Ji daɗin saukakawa a ƙofar ku! Ko tsaftacewa, aikin famfo, kulawa, ko ayyuka masu amfani, ƙwararrun Sabis ɗin Gida na zuwa gare ku - adana lokaci da ƙoƙari yayin tabbatar da inganci da kwanciyar hankali a cikin gidanku.",
        homeServiceBooking:"Danna nan don yin alƙawari yanzu!.",
    },
    appointmentHeadings:{
        educationAppointmentHeading  : "Nadin ilimi",
        healthcareAppointmentHeading : "Alƙawarin kiwon lafiya",
        professionalServiceHeading   : "Alƙawarin sabis na ƙwararru",
        technicalAppointmentHeading  : "Alƙawarin gyaran fasaha"
    },
    userNetworkStatus:{
        status  : "Matsayi",
        online  : "Kan layi",
        offline : "Offline"
    },
    userProfileInfo:{
        userProfileHeading : "Bayanan mai amfani:",
        userProfileName     : "SUNAN:",
        userProfileEmail    : "Imel:",
        userProfileTel      : "WAYAR:",
        userProfileAdmin    : "Admin",
        userProfileNonAdmin : "Ba Admin ba",
        userProfilePassword : "Kalmar sirri:"
    },
    appointmentsInputFields:{
        appointmentsGenderLabel                     : "Jinsi:",
        appointmentsGenderPlaceHolder               : "Da fatan za a shigar da jinsin ku",
        appointmentsAddressLabel                    : "Adireshi:",
        appointmentsAddressPlaceHolder              : "Da fatan za a shigar da adireshin ku",
        appointmentsNextOfKinLabel                  : "Na gaba Kin:",
        appointmentsNextOfKinPlaceHolder            : "Da fatan za a shigar da sunan dangin ku",
        appointmentsNextOfKinAddressLabel           : "Na Gaba Daga Adireshin Kin:",
        appointmentsNextOfKinAddressPlaceHolder     : "Da fatan za a shigar da adireshin dangin ku na gaba",
        appointmentsNextOfKinPhoneNumberLabel       : "Na Gaba Na Lambar Wayar Kin:",
        appointmentsNextOfKinPhoneNumberPlaceHolder : "Da fatan za a shigar da lambar wayar dangin ku na gaba",
        appointmentsTimeLabel                       : "Lokacin Alƙawari:",
        appointmentsTimePlaceHolder                 : "Da fatan za a zaɓi lokacin da ya dace",
        appointmentsDateLabel                       : "Ranar Wa'adin:",
        appointmentsDatePlaceHolder                 : "Da fatan za a zaɓi kwanan kwanan ku mai dacewa",
        appointmentsDescriptionLabel                : "Bayanin Alƙawari:",
        appointmentsDescriptionPlaceHolder          : "Da fatan za a rubuta bayanin alƙawari",
        appointmentButtonParagraph                  : "Ana aiwatarwa....",
        appointmentButtonInnerText                  : "Sallama",
        academicAdvisingHeading                     : "Alƙawari-Nasiha na Ilimi",
        businessConsultationHeading                 : "Alƙawarin Shawarar Kasuwanci",
        careerCounselingHeading                     : "Alƙawari-Nasiha",
        electricalElectronicsRepairHeading          : "Alƙawarin Gyaran Wutar Lantarki/Electronics",
        financialAdvisoryHeading                    : "Alƙawarin Shawarar Kuɗi",
        HealthcareConsultationHeading               : "Alƙawarin Shawarar Lafiya",
        healthcareCounselingSessionHeading          : "Alƙawarin Zama na Ba da Shawarar Lafiya",
        healthcareDentalHeading                     : "Alƙawarin Kula da Lafiyar Haƙori",
        healthcarePhysiotherapySessionHeading       : "Zaman Zama Na Kiwon Lafiyar Jiki",
        healthcareVaccinationHeading                : "Alƙawari na Kula da Lafiya",
        homeServiceHeading                          : "Alƙawarin Sabis na Gida",
        oneOnOneTutoringSessionHeading              : "Wa'adin Zaman Koyarwa Daya-Kan-Daya",
        realEstateAgentHeading                      : "Alƙawarin Wakilin Gidaje"
    },
}
export default hausa;