const igbo = {
    signUpLanguageConfig:{
        signUp:"Debanye aha",
        userNamePlaceholder:"Tinye aha gị",
        emailAddressPlaceholder:"Tinye adreesị email gị",
        passwordPlaceholder:"Tinye paswọọdụ ị nwere ike icheta",
        phoneNumber:"Tinye nọmba ekwentị gị",
        buttonInnerText:"Na-ahazi...",
        inputUsernameLabel:"Aha njirimara:",
        inputEmailLabel:"Adreesị ozi ịntanetị:",
        inputPasswordLabel:"Okwuntughe:",
        inputPhoneLabel:"Nọmba ekwentị:",
    },
    loginLanguageConfig:{
        login:"Banye",
        emailAddressPlaceholder:"Tinye email gị",
        passwordPlaceholder:"Tinye paswọọdụ gị",
        checkBoxInnerText:"Gosi okwuntughe",
        title:"Pịa m ka ịhụ paswọọdụ etinyere",
        paragraphText:"pịa bọtịnụ mgba ọkụ dị n'okpuru ka ịhụ paswọọdụ 👎 ị debanyere.",
        buttonInnerText:"Na-achọpụta...",
        loginEmailInputLabel:"Adreesị ozi ịntanetị:",
        loginPasswordInputLabel:"Okwuntughe:",
    },
    authLanguageConfig:{
        isSignup:"Debanye aha",
        isLogin:"Banye",
        buttonInnerTextLogin:"Banye",
        buttonInnerTextSignup:"Debanye aha",
        paragraphTextAlready:"Ị nwere akaụntụ?",
        paragraphTextDonT:"Ịnweghị akaụntụ?"
    },
    getAUserLanguageConfig:{
        paragraphText:"pịa bọtịnụ dị n'okpuru ka ị nweta nkọwa gị.",
        buttonTitleDisabled:"🚫 Nhazi, biko chere!........",
        buttonTitle:"Pịa ebe a iji nweta👆",
        buttonInnerText:"Nhazi, biko chere!........",
        userNameResponseLi:"Aha njirimara:",
        emailResponseLi:"Email:",
        phoneResponseLi:"Ekwentị:",
        adminResponseLi:"Onye nchịkwa:",
        adminRespYes:"Ee",
        adminRespNo:"Mba",
        hasFetch:"Refetch",
        hasNotFetch:"Weta"
    },
    getAllUsersLanguageConfig:{
        searchPlaceholder:"Chọọ ndị ọrụ",
        buttonInnerTextSearching:"Na-achọ...",
        buttonInnerTextSearch:"Chọọ"
    },
    usersCardsLanguageConfig:{
        username:"Aha njirimara:",
        email:"Email:",
        phone:"Ekwentị:",
        admin:"nye nchịkwa:",
        adminYes:"Ee",
        adminNo:"Mba",
        createdAt:"Emepụtara-na:"  
    },
    descriptionOfProject:"Sistemụ ntinye akwụkwọ nhọpụta bụ ngwa dị iche iche dabere na webụ arụnyere iji kwalite usoro nhazi oge nhọpụta n'ofe mpaghara dị iche iche. Ma ọ na-edobe ndụmọdụ gbasara ahụike, ndụmọdụ mmụta, nnọkọ atụmatụ azụmahịa, ma ọ bụ ịrịọ maka ọrụ ụlọ dị ka nrụzi eletrọnịkị, ndị ọrụ nwere ike nyochaa ọrụ dịnụ, lelee nkọwa ndị dị mkpa, wee kwado nhọpụta n'enweghị nsogbu. Emebere ya na nzaghachi, nnweta na ahụmịhe onye ọrụ, sistemụ ahụ na-erite uru ma ndị na-enye ọrụ site na nhazi nhazi yana ndị ahịa site na ahụmịhe ntinye akwụkwọ na-enweghị nchekasị.",
    homePageDescription:"Nabata na Sistemụ ntinye akwụkwọ oge. Ikpokoro ihe niile dị n'otu ị ga-edobe ọrụ ngwa ngwa dị ka ahụike, agụmakwụkwọ, ndụmọdụ azụmahịa na nrụzi ụlọ. Chekwa oge, nọrọ na nhazi, wee nweta enyemaka ị chọrọ site na iji obere mgbatụ ole na ole.",
    educationAppointment:{
        careerTitle:"Ndụmọdụ ọrụ",
        careerDescription:"Nweta ndụmọdụ ahaziri onwe gị na njem ọrụ gị! Ma ị na-enyocha ohere ọhụrụ, na-ewulite mmalite gị, ma ọ bụ na-akwado maka ajụjụ ọnụ, oge ndụmọdụ ọrụ anyị dị ebe a iji nyere gị aka ịme nzọụkwụ ọzọ na ndụ ọkachamara gị.",
        careerBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
        academicTitle:"Ndụmọdụ agụmakwụkwọ",
        academicDescription:"Nọgide na-eso na ebumnuche agụmakwụkwọ gị! Oge Ndụmọdụ Ọzụzụ anyị na-eduzi gị site na nhọrọ nkuzi, ogo mmụta chọrọ, na ịhazi ụzọ gị maka ngụsị akwụkwọ. Nweta nkwado ị chọrọ ka ịga nke ọma n'ọmụmụ ihe gị.",
        academicBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
        oneOnOneTitle:"Otu-Na-Otu-Nkuzi",
        oneOnOneDescription:"Na-alụ ọgụ na isiokwu? Oge nkuzi otu onye na otu anyị na-enye nkwado ahaziri ahazi iji nyere gị aka ịghọta isiokwu ndị siri ike, kwalite akararị gị, na ịkwalite ntụkwasị obi gị. Soro onye nkuzi dekọọ nnọkọ taa!.",
        oneOnOneBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
    },
    healthcareAppointment:{
        vaccinationTitle:"Ịgba ọgwụ mgbochi ọrịa",
        vaccinationDescription:"Chebe onwe gị na ndị ị hụrụ n'anya site na ịgba ọgwụ mgbochi oge. Debe oge ị ga-enweta ọgwụ mgbochi oge niile ma ọ bụ njem metụtara njem nke ndị ọkachamara ahụike tozuru oke na-elekọta.",
        vaccinationBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
        consultationTitle:"Ndụmọdụ",
        consultationDescription:"Achọrọ ndụmọdụ ahụike? Hazie mkparịta ụka gị na onye na-ahụ maka ahụike nwere ikikere iji kparịta akara ngosi, nweta nchoputa, ma ọ bụ nweta ntuziaka ọkachamara na nchegbu ahụike gị.",
        consultationBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
        counselingTitle:"Oge Ndụmọdụ",
        counselingDescription:"Leba anya n'ọdịmma uche gị. Oge Ndụmọdụ anyị na-enye ohere nchekwa, nzuzo iji gwa ndị ndụmọdụ a zụrụ azụ gbasara nrụgide, nchekasị, mmekọrịta, ma ọ bụ ihe ịma aka onwe onye ndị ọzọ.",
        counselingBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
        dentalTitle:"Nlekọta ahụike eze",
        dentalDescription:"Mee ka ọnụ ọchị gị dị mma! Debe oge nhọpụta eze maka nhicha, nlele, ndochi, ma ọ bụ mkpa nlekọta ọnụ ndị ọzọ. Ndị ọkachamara na-ahụ maka eze anyị nọ ebe a iji hụ na ezé gị na chịngọm na-anọ n'ụdị dị mma.",
        dentalBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
        physiotherapyTitle:"Physiotherapy",
        physiotherapyDescription:"Weghachite ma nwetaghachi ume site na ọkachamara physiotherapy. Ma ọ bụ mmegharị ahụ mgbe mmerụ ahụ gasịrị, mgbu na-adịghị ala ala, ma ọ bụ okwu mkpagharị, ndị na-ahụ maka ọgwụgwọ anyị ga-enyere gị aka ịkwaga nke ọma ma nwee ahụ iru ala.",
        physiotherapyBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!."
    },
    professionalServiceAppointment:{
        businessConsultTitle:"Ndụmọdụ azụmahịa",
        businessConsultDescription:"Nweta nghọta ndị ọkachamara iji kwalite azụmahịa gị. Ma ị bụ onye mmalite ma ọ bụ ụlọ ọrụ guzosiri ike, ndị na-ahụ maka azụmaahịa anyị na-enye ntụzịaka usoro, idozi nsogbu na nkwado atụmatụ iji nyere gị aka itule nke ọma na imezu ebumnuche gị.",
        businessConsultBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
        financialAdvisingTitle:"Ndụmọdụ gbasara ego",
        financialAdvisingDescription:"Jiri ndụmọdụ ndị ọkachamara were njikwa ego gị. Ndị ndụmọdụ gbasara ego anyị gbaara agbaziri na-enyere gị aka ịhazi atụmatụ maka ọdịnihu, jikwaa itinye ego, belata ụgwọ, ma mee mkpebi ziri ezi iji chekwaa ọdịmma ego gị.",
        financialAdvisingBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
        realEstateAgentTitle:"Onye nnọchi anya ụlọ",
        realEstateAgentDescription:"Jiri obi ike chọta ihe onwunwe gị zuru oke. Ndị na-ahụ maka ụlọ anyị nwere ahụmahụ na-enye ọrụ ahaziri iche iji nyere gị aka ịzụrụ, ree, ma ọ bụ ịgbazite ụlọ na oghere azụmahịa - na-eduzi gị n'ụzọ ọ bụla site na iji ọkachamara mpaghara.",
        realEstateAgentBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
    },
    technicalAppointment:{
        electricalElectronicsTitle:"Mmezi Eletriki/Electronics",
        electricalElectronicsDescription:"Ị nwere ngwa ma ọ bụ ngwaọrụ ezighi ezi? Ọrụ mmezi eletriki na eletrọnịkị anyị na-enye ndozi ngwa ngwa, nke a pụrụ ịdabere na ya maka ihe niile site na nsogbu wiring ruo na ngwa agbajiri agbaji. Debe nnọkọ gị na ọkachamara nka ma mee ka ihe na-arụ ọrụ ọzọ.",
        electricalElectronicsBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
        homeServiceTitle:"Ọrụ ụlọ",
        homeServiceDescription:"Nwee obi ụtọ n'ọnụ ụzọ gị! Ma ọ bụ nhicha, ịgba mmiri, ịrụzi ma ọ bụ ọrụ aka, ndị ọkachamara na-ahụ maka ọrụ ụlọ na-abịakwute gị - na-echekwa oge na mbọ ma na-ahụ na ịdịmma na nkasi obi n'ụlọ gị.",
        homeServiceBooking:"Pịa ebe a ka akwụkwọ ọkwa ugbu a!.",
    },
    appointmentHeadings:{
        educationAppointmentHeading : "Nhọpụta agụmakwụkwọ",
        healthcareAppointmentHeading : "Oge nlekọta ahụike",
        professionalServiceHeading : "Oge ọrụ ọkachamara",
        technicalAppointmentHeading : "Nrụzi ọrụ nka"
    },
    userNetworkStatus:{
        status  : "Ọnọdụ",
        online  : "Online",
        offline : "Na-anọghị n'ịntanetị"
    },
    userProfileInfo:{
        userProfileHeading : "Profaịlụ onye ọrụ:",
        userProfileName     : "AHA:",
        userProfileEmail    : "EMAIL:",
        userProfileTel      : "Ekwentị:",
        userProfileAdmin    : "Admin",
        userProfileNonAdmin : "Ndị na-abụghị Admin",
        userProfilePassword : "PASSWORD:"
    },
    appointmentsInputFields:{
        appointmentsGenderLabel                     : "okike:",
        appointmentsGenderPlaceHolder               : "Biko tinye okike gị",
        appointmentsAddressLabel                    : "adreesị:",
        appointmentsAddressPlaceHolder              : "Biko tinye adreesị gị",
        appointmentsNextOfKinLabel                  : "Ọzọ nke Kin:",
        appointmentsNextOfKinPlaceHolder            : "Biko tinye aha ndị ikwu gị",
        appointmentsNextOfKinAddressLabel           : "Ọzọ nke Kin Adreesị:",
        appointmentsNextOfKinAddressPlaceHolder     : "Biko tinye adreesị ndị ikwu gị",
        appointmentsNextOfKinPhoneNumberLabel       : "Nọmba ekwentị Kin na-esote:",
        appointmentsNextOfKinPhoneNumberPlaceHolder : "Biko tinye nọmba ekwentị ndị ikwu gị",
        appointmentsTimeLabel                       : "Oge nhọpụta:",
        appointmentsTimePlaceHolder                 : "Biko họrọ oge gị dị mma",
        appointmentsDateLabel                       : "Ụbọchị nhọpụta:",
        appointmentsDatePlaceHolder                 : "Biko họrọ ụbọchị dabara adaba",
        appointmentsDescriptionLabel                : "Nkọwa oge:",
        appointmentsDescriptionPlaceHolder          : "Biko dee nkọwa ọkwa",
        appointmentButtonParagraph                  : "Na-ahazi....",
        appointmentButtonInnerText                  : "Nyefee",
        academicAdvisingHeading                     : "Oge mmuta-ndụmọdụ",
        businessConsultationHeading                 : "Oge ndụmọdụ azụmahịa",
        careerCounselingHeading                     : "Oge ndụmọdụ ọrụ",
        electricalElectronicsRepairHeading          : "Oge nrụzi Eletriki/Electronics",
        financialAdvisoryHeading                    : "Oge Ndụmọdụ gbasara ego",
        HealthcareConsultationHeading               : "Ntụle nlekọta ahụike",
        healthcareCounselingSessionHeading          : "Oge Oge Ndụmọdụ nlekọta ahụike",
        healthcareDentalHeading                     : "Oge nlekọta ahụike eze",
        healthcarePhysiotherapySessionHeading       : "Nlekọta ahụike physiotherapy oge oge",
        healthcareVaccinationHeading                : "Oge ịgba ọgwụ mgbochi ahụike ahụike",
        homeServiceHeading                          : "Oge ọrụ ụlọ",
        oneOnOneTutoringSessionHeading              : "Oge Nkuzi Otu-Na Otu",
        realEstateAgentHeading                      : "Nhọpụta onye nnọchi anya ụlọ"
    },
}
export default igbo;