const spanish = {
    signUpLanguageConfig:{
        signUp:"Inscribirse",
        userNamePlaceholder:"Introduce tu nombre",
        emailAddressPlaceholder:"Introduzca su dirección de correo electrónico",
        passwordPlaceholder:"Introduzca una contraseña que pueda recordar",
        phoneNumber:"Introduce tu número de teléfono",
        buttonInnerText:"Tratamiento...",
        inputUsernameLabel:"Nombre de usuario:",
        inputEmailLabel:"Dirección de correo electrónico:",
        inputPasswordLabel:"Contraseña:",
        inputPhoneLabel:"Número de teléfono:",
    },
    loginLanguageConfig:{
        login:"Acceso",
        emailAddressPlaceholder:"Introduce tu correo electrónico",
        passwordPlaceholder:"Ingrese su contraseña",
        checkBoxInnerText:"Mostrar contraseña",
        title:"Haz clic en mí para ver la contraseña ingresada",
        paragraphText:"Haga clic en el interruptor/botón a continuación para ver la contraseña que ingresó.",
        buttonInnerText:"Autenticando...",
        loginEmailInputLabel:"Dirección de correo electrónico:",
        loginPasswordInputLabel:"Contraseña:",
    },
    authLanguageConfig:{
        isSignup:"Inscribirse",
        isLogin:"Acceso",
        buttonInnerTextLogin:"Acceso",
        buttonInnerTextSignup:"Inscribirse",
        paragraphTextAlready:"¿Ya tienes una cuenta?",
        paragraphTextDonT:"¿No tienes una cuenta?"
    },
    getAUserLanguageConfig:{
        paragraphText:"Haga clic en el botón a continuación para obtener sus datos.",
        buttonTitleDisabled:"🚫 Procesando, por favor espere!........",
        buttonTitle:"Haga clic aquí para obtener👆",
        buttonInnerText:"Procesando, por favor espere!........",
        userNameResponseLi:"Nombre de usuario:",
        emailResponseLi:"Correo electrónico:",
        phoneResponseLi:"Teléfono:",
        adminResponseLi:"Administración:",
        adminRespYes:"Sí",
        adminRespNo:"No",
        hasFetch:"Recuperar",
        hasNotFetch:"Buscar"
    },
    getAllUsersLanguageConfig:{
        searchPlaceholder:"Buscar usuarios/Buscar usuarias",
        buttonInnerTextSearching:"Búsqueda...",
        buttonInnerTextSearch:"Buscar"
    },
    usersCardsLanguageConfig:{
        username:"Nombre de usuario:",
        email:"Correo electrónico:",
        phone:"Teléfono:",
        admin:"Administración:",
        adminYes:"Sí",
        adminNo:"No",
        createdAt:"Creado en:"  
    },
    descriptionOfProject:"El Sistema de Reserva de Citas es una aplicación web versátil diseñada para agilizar la programación de citas en múltiples sectores. Ya sea para reservar una consulta médica, asesoramiento educativo, una sesión de estrategia empresarial o para solicitar un servicio a domicilio como la reparación de aparatos electrónicos, los usuarios pueden explorar los servicios disponibles, ver detalles esenciales y confirmar citas sin problemas. Diseñado con capacidad de respuesta, accesibilidad y una experiencia de usuario optimizada, el sistema beneficia tanto a los proveedores de servicios mediante una programación organizada como a los clientes mediante una experiencia de reserva intuitiva y sin complicaciones.",
    homePageDescription:"Bienvenido al Sistema de Reserva de Citas. Tu plataforma integral para reservar rápidamente servicios como salud, educación, consultas empresariales y reparaciones del hogar. Ahorra tiempo, organízate y obtén la ayuda que necesitas con solo unos clics.",
    educationAppointment:{
        careerTitle:"Orientación profesional",
        careerDescription:"¡Recibe asesoramiento personalizado para tu trayectoria profesional! Ya sea que estés explorando nuevas oportunidades, desarrollando tu currículum o preparándote para entrevistas, nuestras sesiones de Orientación Profesional te ayudarán a dar el siguiente paso en tu vida profesional.",
        careerLink:"¡Recibe asesoramiento personalizado para tu trayectoria profesional! Ya sea que estés explorando nuevas oportunidades, desarrollando tu currículum o preparándote para entrevistas, nuestras sesiones de Orientación Profesional te ayudarán a dar el siguiente paso en tu vida profesional.",
        careerBooking:"¡Haga clic aquí para reservar cita ahora!.",
        academicTitle:"Asesoría académica",
        academicDescription:"¡Mantén tus metas académicas en marcha! Nuestras sesiones de Asesoría Académica te guiarán en la selección de cursos, los requisitos del título y la planificación de tu camino hacia la graduación. Obtén el apoyo que necesitas para alcanzar el éxito en tus estudios.",
        academicBooking:"¡Haga clic aquí para reservar cita ahora!.",
        oneOnOneTitle:"Tutoría individual",
        oneOnOneDescription:"¿Tienes dificultades con alguna materia? Nuestras tutorías individuales te ofrecen apoyo personalizado para ayudarte a comprender temas difíciles, mejorar tus calificaciones y aumentar tu confianza. ¡Reserva una sesión con un tutor hoy mismo!",
        oneOnOneBooking:"¡Haga clic aquí para reservar cita ahora!.",
    },
    healthcareAppointment:{
        vaccinationTitle:"Vacunación",
        vaccinationDescription:"Protéjase y proteja a sus seres queridos con vacunas oportunas. Reserve una cita para recibir vacunas de rutina o para viajes administradas por profesionales de la salud calificados.",
        vaccinationBooking:"¡Haga clic aquí para reservar cita ahora!.",
        consultationTitle:"Consulta",
        consultationDescription:"¿Necesitas consejo médico? Programa una consulta con un profesional de la salud certificado para hablar sobre tus síntomas, obtener diagnósticos o recibir orientación profesional sobre tus problemas de salud.",
        consultationBooking:"¡Haga clic aquí para reservar cita ahora!.",
        counselingTitle:"Sesión de asesoramiento",
        counselingDescription:"Cuida tu bienestar mental. Nuestras sesiones de terapia ofrecen un espacio seguro y confidencial para hablar con consejeros capacitados sobre el estrés, la ansiedad, las relaciones y otros desafíos personales.",
        counselingBooking:"¡Haga clic aquí para reservar cita ahora!.",
        dentalTitle:"Atención médica dental",
        dentalDescription:"¡Mantén tu sonrisa sana! Reserva una cita dental para limpiezas, revisiones, empastes u otras necesidades de cuidado bucal. Nuestros profesionales dentales están aquí para garantizar que tus dientes y encías se mantengan en perfectas condiciones.",
        dentalBooking:"¡Haga clic aquí para reservar cita ahora!.",
        physiotherapyTitle:"Fisioterapia",
        physiotherapyDescription:"Recupérate y recupera fuerzas con fisioterapia experta. Ya sea rehabilitación post-lesión, dolor crónico o problemas de movilidad, nuestros terapeutas te ayudarán a moverte mejor y sentirte mejor.",
        physiotherapyBooking:"¡Haga clic aquí para reservar cita ahora!."
    },
    professionalServiceAppointment:{
        businessConsultTitle:"Consultoría de Negocios",
        businessConsultDescription:"Obtén información experta para impulsar el crecimiento de tu negocio. Tanto si eres una startup como una empresa consolidada, nuestros consultores te ofrecen orientación estratégica, resolución de problemas y apoyo en la planificación para ayudarte a crecer eficazmente y alcanzar tus objetivos.",
        businessConsultBooking:"¡Haga clic aquí para reservar cita ahora!.",
        financialAdvisingTitle:"Asesoramiento financiero",
        financialAdvisingDescription:"Tome el control de sus finanzas con asesoría profesional. Nuestros asesores financieros certificados le ayudan a planificar su futuro, gestionar inversiones, reducir deudas y tomar decisiones informadas para asegurar su bienestar financiero.",
        financialAdvisingBooking:"¡Haga clic aquí para reservar cita ahora!.",
        realEstateAgentTitle:"Agente inmobiliario",
        realEstateAgentDescription:"Encuentre la propiedad perfecta con confianza. Nuestros agentes inmobiliarios con amplia experiencia le ofrecen un servicio personalizado para ayudarle a comprar, vender o alquilar viviendas y locales comerciales, guiándolo en cada paso del proceso con su experiencia local.",
        realEstateAgentBooking:"¡Haga clic aquí para reservar cita ahora!.",
    },
    technicalAppointment:{
        electricalElectronicsTitle:"Reparación eléctrica/electrónica",
        electricalElectronicsDescription:"¿Tiene un electrodoméstico o dispositivo defectuoso? Nuestro servicio de reparación de aparatos eléctricos y electrónicos ofrece soluciones rápidas y fiables para todo, desde problemas de cableado hasta aparatos averiados. Reserve una sesión con un técnico cualificado y deje que todo vuelva a funcionar.",
        electricalElectronicsBooking:"¡Haga clic aquí para reservar cita ahora!.",
        homeServiceTitle:"Servicio a domicilio",
        homeServiceDescription:"¡Disfrute de la comodidad en su hogar! Ya sea limpieza, plomería, mantenimiento o tareas de mantenimiento, nuestros profesionales de Servicios a Domicilio van a su domicilio, ahorrándole tiempo y esfuerzo, y garantizando calidad y comodidad en su hogar.",
        homeServiceBooking:"¡Haga clic aquí para reservar cita ahora!.",
    },
    appointmentHeadings:{
        educationAppointmentHeading : "Cita educativa",
        healthcareAppointmentHeading : "Cita de atención médica",
        professionalServiceHeading : "Cita de servicio profesional",
        technicalAppointmentHeading : "Cita de reparación técnica"
    },
    userNetworkStatus:{
        status  : "Estado",
        online  : "En línea",
        offline : "Desconectada"
    },
    userProfileInfo:{
        userProfileHeading : "Perfil de usuario:",
        userProfileParagraph : "Para ver sus datos aquí, debe obtenerlos haciendo clic en 'Perfil de usuario' en la barra lateral (los 3 puntos verticales) en la parte superior derecha de la página principal.",
        userProfileName     : "NOMBRE:",
        userProfileEmail    : "CORREO ELECTRÓNICO:",
        userProfileTel      : "TELÉFONO:",
        userProfileAdmin    : "Administrador",
        userProfileNonAdmin : "No administrador",
        userProfilePassword : "CONTRASEÑA:"
    },
    appointmentsInputFields:{
        appointmentsGenderLabel                     : "Género:",
        appointmentsGenderPlaceHolder               : "Por favor, introduzca su género",
        appointmentsAddressLabel                    : "DIRECCIÓN:",
        appointmentsAddressPlaceHolder              : "Por favor ingrese su dirección",
        appointmentsNextOfKinLabel                  : "Pariente más cercano:",
        appointmentsNextOfKinPlaceHolder            : "Por favor ingrese el nombre de su pariente más cercano",
        appointmentsNextOfKinAddressLabel           : "Dirección del pariente más cercano:",
        appointmentsNextOfKinAddressPlaceHolder     : "Por favor ingrese la dirección de su pariente más cercano",
        appointmentsNextOfKinPhoneNumberLabel       : "Número de teléfono del pariente más cercano:",
        appointmentsNextOfKinPhoneNumberPlaceHolder : "Por favor ingrese el número de teléfono de su pariente más cercano",
        appointmentsTimeLabel                       : "Hora de la cita:",
        appointmentsTimePlaceHolder                 : "Por favor, elija el horario que le convenga.",
        appointmentsDateLabel                       : "Fecha de la cita:",
        appointmentsDatePlaceHolder                 : "Por favor, elija la fecha que le convenga",
        appointmentsDescriptionLabel                : "Descripción de la cita:",
        appointmentsDescriptionPlaceHolder          : "Por favor escriba la descripción de la cita.",
        appointmentButtonParagraph                  : "Tratamiento....",
        appointmentButtonInnerText                  : "Entregar",
        academicAdvisingHeading                     : "Nombramiento de Asesoría Académica",
        businessConsultationHeading                 : "Cita de consulta empresarial",
        careerCounselingHeading                     : "Cita de orientación profesional",
        electricalElectronicsRepairHeading          : "Cita para reparación de aparatos eléctricos y electrónicos",
        financialAdvisoryHeading                    : "Nombramiento de Asesoría Financiera",
        HealthcareConsultationHeading               : "Cita de consulta de salud",
        healthcareCounselingSessionHeading          : "Cita para sesión de asesoramiento en salud",
        healthcareDentalHeading                     : "Cita para atención dental",
        healthcarePhysiotherapySessionHeading       : "Cita para sesión de fisioterapia sanitaria",
        healthcareVaccinationHeading                : "Cita de vacunación para atención médica",
        homeServiceHeading                          : "Cita de servicio a domicilio",
        oneOnOneTutoringSessionHeading              : "Cita para sesión de tutoría individual",
        realEstateAgentHeading                      : "Nombramiento de agente inmobiliario"
    },
}
export default spanish;