const yoruba = {
    signUpLanguageConfig:{
        signUp:"Forukọsilẹ",
        userNamePlaceholder:"Tẹ orukọ rẹ sii",
        emailAddressPlaceholder:"Tẹ adirẹsi imeeli rẹ sii",
        passwordPlaceholder:"Tẹ ọrọ igbaniwọle sii ti o le ranti",
        phoneNumber:"Tẹ nọmba foonu rẹ sii",
        buttonInnerText:"Nṣiṣẹ...",
        inputUsernameLabel:"Orukọ olumulo:",
        inputEmailLabel:"Adirẹsi imeeli:",
        inputPasswordLabel:"Ọrọigbaniwọle:",
        inputPhoneLabel:"Nomba fonu:",
    },
    loginLanguageConfig:{
        login:"Wo ile",
        emailAddressPlaceholder:"Tẹ imeeli rẹ sii",
        passwordPlaceholder:"Tẹ ọrọ igbaniwọle rẹ sii",
        checkBoxInnerText:"Ṣe afihan Ọrọigbaniwọle",
        title:"Tẹ mi lati wo ọrọ igbaniwọle ti a tẹ sii",
        paragraphText:"tẹ bọtini yipada / bọtini isalẹ lati wo ọrọ igbaniwọle 👎 ti o tẹ.",
        buttonInnerText:"Ijeri...",
        loginEmailInputLabel:"Adirẹsi imeeli:",
        loginPasswordInputLabel:"Ọrọigbaniwọle:",
    },
    authLanguageConfig:{
        isSignup:"Forukọsilẹ",
        isLogin:"Wo ile",
        buttonInnerTextLogin:"Wo ile",
        buttonInnerTextSignup:"Forukọsilẹ",
        paragraphTextAlready:"Ti ni iroyin tẹlẹ?",
        paragraphTextDonT:"Ṣe ko ni akọọlẹ kan?"
    },
    getAUserLanguageConfig:{
        paragraphText:"tẹ bọtini ni isalẹ lati gba awọn alaye rẹ.",
        buttonTitleDisabled:"🚫 Ṣiṣẹ, jọwọ duro!........",
        buttonTitle:"Tẹ ibi lati mu👆",
        buttonInnerText:"Ṣiṣẹ, jọwọ duro!........",
        userNameResponseLi:"Orukọ olumulo:",
        emailResponseLi:"Imeeli:",
        phoneResponseLi:"Foonu:",
        adminResponseLi:"Abojuto:",
        adminRespYes:"Bẹẹni",
        adminRespNo:"Rara",
        hasFetch:"Refetch",
        hasNotFetch:"Mu"
    },
    getAllUsersLanguageConfig:{
        searchPlaceholder:"Wa awọn olumulo",
        buttonInnerTextSearching:"N wa...",
        buttonInnerTextSearch:"Wa"
    },
    usersCardsLanguageConfig:{
        username:"Orukọ olumulo:",
        email:"Imeeli:",
        phone:"Foonu:",
        admin:"Abojuto:",
        adminYes:"Bẹẹni",
        adminNo:"Rara",
        createdAt:"Ti ṣẹda-ni:"  
    },
    descriptionOfProject:"Eto Ifiweranṣẹ ipinnu lati pade jẹ ohun elo ti o da lori oju opo wẹẹbu ti o wapọ ti a ṣe lati mu ilana ṣiṣe ṣiṣe eto awọn ipinnu lati pade kọja awọn apa lọpọlọpọ. Boya o n fowo si ijumọsọrọ iṣoogun kan, imọran eto-ẹkọ, igba ilana iṣowo, tabi beere iṣẹ ile kan bii atunṣe ẹrọ itanna, awọn olumulo le ṣawari awọn iṣẹ ti o wa, wo awọn alaye pataki, ati jẹrisi awọn ipinnu lati pade lainidi. Ti a ṣe apẹrẹ pẹlu idahun, iraye si, ati iriri olumulo ni ọkan, eto naa ni anfani fun awọn olupese iṣẹ mejeeji nipasẹ ṣiṣe eto ati awọn alabara nipasẹ oye, iriri ifiṣura laisi wahala.",
    homePageDescription:"Kaabo si Eto Fowo si ipinnu lati pade. Syeed gbogbo-ni-ọkan rẹ lati yara iwe awọn iṣẹ bii ilera, eto-ẹkọ, awọn ijumọsọrọ iṣowo, ati awọn atunṣe ile. Fi akoko pamọ, duro ṣeto, ki o gba iranlọwọ ti o nilo pẹlu awọn tẹ ni kia kia diẹ.",
    educationAppointment:{
        careerTitle:"Igbaninimoran Iṣẹ",
        careerDescription:"Gba imọran ti ara ẹni lori irin-ajo iṣẹ rẹ! Boya o n ṣawari awọn aye tuntun, ṣiṣe atunbere rẹ, tabi ngbaradi fun awọn ifọrọwanilẹnuwo, awọn akoko Igbaninimoran Iṣẹ wa wa nibi lati ṣe iranlọwọ fun ọ lati ṣe igbesẹ atẹle ni igbesi aye alamọdaju rẹ.",
        careerBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
        academicTitle:"Imọran ẹkọ",
        academicDescription:"Duro lori ọna pẹlu awọn ibi-afẹde eto-ẹkọ rẹ! Awọn akoko Igbaninimoran Ẹkọ wa ṣe itọsọna fun ọ nipasẹ yiyan iṣẹ-ẹkọ, awọn ibeere alefa, ati gbero ọna rẹ si ayẹyẹ ipari ẹkọ. Gba atilẹyin ti o nilo lati ṣaṣeyọri ninu awọn ẹkọ rẹ.",
        academicBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
        oneOnOneTitle:"Ọkan-Lori-Ọkan-Tutoring",
        oneOnOneDescription:"Ijakadi pẹlu koko-ọrọ kan? Awọn akoko Ikẹkọ Ọkan-lori-Ọkan wa n pese atilẹyin ti o ni ibamu lati ṣe iranlọwọ fun ọ lati loye awọn koko-ọrọ ti o nira, mu awọn ipele rẹ dara si, ati igbelaruge igbẹkẹle rẹ. Ṣe iwe igba kan pẹlu olukọ loni!.",
        oneOnOneBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
    },
    healthcareAppointment:{
        vaccinationTitle:"Ajesara",
        vaccinationDescription:"Daabobo ararẹ ati awọn ayanfẹ rẹ pẹlu awọn ajesara akoko. Ṣe ipinnu lati pade lati gba ilana-iṣe tabi awọn ajesara ti o ni ibatan irin-ajo ti a nṣakoso nipasẹ awọn alamọdaju ilera ti o peye.",
        vaccinationBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
        consultationTitle:"Ijumọsọrọ",
        consultationDescription:"Nilo imọran iṣoogun? Ṣe eto ijumọsọrọ pẹlu olupese ilera ti o ni iwe-aṣẹ lati jiroro awọn aami aisan, gba awọn iwadii aisan, tabi gba itọnisọna alamọdaju lori awọn ifiyesi ilera rẹ.",
        consultationBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
        counselingTitle:"Igba Igbaninimoran",
        counselingDescription:"Ṣe abojuto ilera ọpọlọ rẹ. Awọn akoko Igbaninimoran wa n funni ni ailewu, aaye aṣiri lati ba awọn oludamọran ikẹkọ sọrọ nipa wahala, aibalẹ, awọn ibatan, tabi awọn italaya ti ara ẹni miiran.",
        counselingBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
        dentalTitle:"Itoju Ehín",
        dentalDescription:"Jeki ẹrin rẹ ni ilera! Iwe ipinnu lati pade ehín fun awọn mimọ, awọn ayẹwo, awọn kikun, tabi awọn iwulo itọju ẹnu miiran. Awọn alamọdaju ehín wa nibi lati rii daju pe eyin ati awọn gomu duro ni apẹrẹ nla.",
        dentalBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
        physiotherapyTitle:"Ẹkọ-ara",
        physiotherapyDescription:"Bọsipọ ki o tun gba agbara pẹlu iwé physiotherapy. Boya o jẹ atunṣe ipalara lẹhin-ipalara, irora onibaje, tabi awọn ọran arinbo, awọn oniwosan aisan yoo ran ọ lọwọ lati gbe daradara ati ki o lero dara julọ.",
        physiotherapyBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!."
    },
    professionalServiceAppointment:{
        businessConsultTitle:"Ijumọsọrọ Iṣowo",
        businessConsultDescription:"Gba awọn oye amoye lati dagba iṣowo rẹ. Boya o jẹ ibẹrẹ tabi ile-iṣẹ ti iṣeto, awọn alamọran iṣowo wa nfunni ni itọsọna ilana, ipinnu iṣoro, ati atilẹyin igbero lati ṣe iranlọwọ fun ọ ni iwọn daradara ati ṣaṣeyọri awọn ibi-afẹde rẹ.",
        businessConsultBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
        financialAdvisingTitle:"Owo Igbaninimoran",
        financialAdvisingDescription:"Ṣe iṣakoso awọn inawo rẹ pẹlu imọran ọjọgbọn. Awọn oludamọran inawo ti a fọwọsi ṣe iranlọwọ fun ọ lati gbero fun ọjọ iwaju, ṣakoso awọn idoko-owo, dinku gbese, ati ṣe awọn ipinnu alaye lati ni aabo alafia inawo rẹ.",
        financialAdvisingBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
        realEstateAgentTitle:"Real Estate Aṣoju",
        realEstateAgentDescription:"Wa ohun-ini pipe rẹ pẹlu igboiya. Awọn aṣoju ohun-ini gidi ti o ni iriri pese iṣẹ ti ara ẹni lati ṣe iranlọwọ fun ọ lati ra, ta, tabi yalo awọn ile ati awọn aaye iṣowo - didari ọ ni gbogbo igbesẹ ti ọna pẹlu oye agbegbe.",
        realEstateAgentBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
    },
    technicalAppointment:{
        electricalElectronicsTitle:"Itanna/Electronics Tunṣe",
        electricalElectronicsDescription:"Njẹ ohun elo tabi ẹrọ ti ko tọ? Iṣẹ Atunṣe Itanna ati Itanna Itanna nfunni ni iyara, awọn atunṣe igbẹkẹle fun ohun gbogbo lati awọn ọran onirin si awọn ohun elo fifọ. Ṣe iwe igba kan pẹlu onimọ-ẹrọ ti oye ati gba awọn nkan ṣiṣẹ lẹẹkansi.",
        electricalElectronicsBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
        homeServiceTitle:"Iṣẹ ile",
        homeServiceDescription:"Gbadun wewewe ni ẹnu-ọna rẹ! Boya o jẹ mimọ, fifi ọpa omi, itọju, tabi awọn iṣẹ afọwọṣe, awọn alamọja Iṣẹ Ile wa wa si ọ— fifipamọ akoko ati igbiyanju lakoko ṣiṣe idaniloju didara ati itunu ninu ile rẹ.",
        homeServiceBooking:"Tẹ ibi lati ṣe ipinnu lati pade ni bayi!.",
    },
    appointmentHeadings:{
        educationAppointmentHeading  : "Ipinnu eto-ẹkọ",
        healthcareAppointmentHeading : "Ilera pade",
        professionalServiceHeading   : "Ọjọgbọn iṣẹ ipinnu lati pade",
        technicalAppointmentHeading  : "Ipinnu atunṣe imọ-ẹrọ"
    },
    userNetworkStatus:{
        status  : "Ipo",
        online  : "Online",
        offline : "Aisinipo"
    },
    userProfileInfo:{
        userProfileHeading   : "Profaili olumulo:",
        userProfileParagraph : "Lati le rii awọn alaye rẹ nibi, o ni lati mu awọn alaye rẹ wa nipa titẹ 'Profaili olumulo' ni ẹgbẹ-ọpa (aami inaro 3) ni apa ọtun oke ti oju-iwe akọkọ.",
        userProfileName      : "ORUKO:",
        userProfileEmail     : "EMAIL:",
        userProfileTel       : "FOONU:",
        userProfileAdmin     : "Abojuto",
        userProfileNonAdmin  : "Ti kii ṣe Alakoso",
        userProfilePassword  : "Ọrọ igbaniwọle:"
    },
    appointmentsInputFields:{
        appointmentsGenderLabel                     : "abo:",
        appointmentsGenderPlaceHolder               : "Jọwọ tẹ akọ-abo rẹ sii",
        appointmentsAddressLabel                    : "Adirẹsi:",
        appointmentsAddressPlaceHolder              : "Jọwọ tẹ adirẹsi rẹ sii",
        appointmentsNextOfKinLabel                  : "Nigbamii ti Kin:",
        appointmentsNextOfKinPlaceHolder            : "Jọwọ tẹ orukọ ibatan ibatan rẹ sii",
        appointmentsNextOfKinAddressLabel           : "Itele ti Adirẹsi Kin:",
        appointmentsNextOfKinAddressPlaceHolder     : "Jọwọ tẹ adirẹsi ibatan ibatan rẹ sii",
        appointmentsNextOfKinPhoneNumberLabel       : "Nigbamii ti Nọmba Foonu Kin:",
        appointmentsNextOfKinPhoneNumberPlaceHolder : "Jọwọ tẹ nọmba foonu ti ibatan rẹ ti o tẹle",
        appointmentsTimeLabel                       : "Àkókò Ìpàdé:",
        appointmentsTimePlaceHolder                 : "Jọwọ yan akoko irọrun rẹ",
        appointmentsDateLabel                       : "Ọjọ Ipinnu:",
        appointmentsDatePlaceHolder                 : "Jọwọ yan ọjọ irọrun rẹ",
        appointmentsDescriptionLabel                : "Apejuwe Ipinnu:",
        appointmentsDescriptionPlaceHolder          : "Jọwọ kọ apejuwe ipinnu lati pade",
        appointmentButtonParagraph                  : "Nṣiṣẹ….",
        appointmentButtonInnerText                  : "Fi silẹ",
        academicAdvisingHeading                     : "Omowe- Igbaninimoran ipinnu",
        businessConsultationHeading                 : "Ijumọsọrọ Iṣowo",
        careerCounselingHeading                     : "Ipinnu Igbaninimoran Iṣẹ",
        electricalElectronicsRepairHeading          : "Itanna/Electronics Tunṣe pade",
        financialAdvisoryHeading                    : "Owo Advisory ipinnu lati pade",
        HealthcareConsultationHeading               : "Ijumọsọrọ Ilera",
        healthcareCounselingSessionHeading          : "Ipinnu Ikoni Igbaninimoran Ilera",
        healthcareDentalHeading                     : "Iṣeduro Itọju Ehín",
        healthcarePhysiotherapySessionHeading       : "Ilera Itọju Ẹjẹ ara Ikoni ipade",
        healthcareVaccinationHeading                : "Ilera ajesara pade",
        homeServiceHeading                          : "Home Service pade",
        oneOnOneTutoringSessionHeading              : "Ipinnu Ikoni Olukọni Ọkan-Lori-Ọkan",
        realEstateAgentHeading                      : "Ipinnu Aṣoju Ohun-ini gidi"
    },
}
export default yoruba;